apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.Appname }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.Appname }}
  minReplicas: {{ .Values.Autoscaler.minReplicas }}
  maxReplicas: {{ .Values.Autoscaler.maxReplicas }}
  metrics: 
  - type: Resource
    resource:
      name: memory 
      target:
        type: Utilization 
        averageUtilization: {{ .Values.Autoscaler.memory.averageValue }}
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: {{ .Values.Autoscaler.cpu.averageValue }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.Autoscaler.scaleDown.stabilizationWindowSeconds }}
      policies:
      {{- range .Values.Autoscaler.scaleDown.rules }}
      - type: {{ .type }}
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
      {{- end }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.Autoscaler.scaleUp.stabilizationWindowSeconds }}
      policies:
      {{- range .Values.Autoscaler.scaleUp.rules }}
      - type: {{ .type }}
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
      {{- end }}
      selectPolicy: Max
