
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32090
        hostPort: 32090
        protocol: TCP
  - role: control-plane
  - role: control-plane
  - role: worker
  - role: worker

